language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

script:
  - cargo build --verbose
  - cargo build --verbose --examples
  - cargo test --verbose
