[package]
name = "demo-parser"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]

[profile.release]
lto = true

[dependencies]
error-chain = "0.11"
memmap = "0.5"
quick-error = "1"

[dependencies.nom]
version = "3.2"
features = ["verbose-errors"]
